### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by ghost** [royspace/twitter-following-list-exporter#1]
Structure of the Returned JSON possibly changed recently, script needs adjustment.

`python twitter-following-list-exporter.py
`
```
Processing URLs:   0%|                                                                                                                                              | 0/625 [00:04<?, ?URL/s]
Traceback (most recent call last):
  File "D:\twitter-following-list-exporter-main\twitter-following-list-exporter.py", line 84, in <module>
    author_info = extract_author_info(json_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\twitter-following-list-exporter-main\twitter-following-list-exporter.py", line 29, in extract_author_info
    author_info = data[0][1]['author']
                  ~~~~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by royspace** [comment]
I acknowledged this error a few days ago. You likely need to upgrade your gallery-dl to the newest version and it will work

**Comment by ghost** [comment]
Yes, its a problem with gallery-dl. Turns out logging with username and password does not work for me so I've changed to cookies method and it works now.
