### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by iWajdi** [royspace/twitter-following-list-exporter#2]
Sorry for the unclear title, but I tried to run the scripts on both a virtual and local environment each time i get the same error. 

![image](https://github.com/user-attachments/assets/39616e0f-d46c-4585-b0c9-17312ed9d58b)

The issue starts when python3 twitter-following-list-exporter.py script kicks in. 
I tried to skip that part and create the csv file myself the rest of the scripts :
* python3 twitter-following-list-exporter-html.py
* python3 convert_v2.py

They are working but they don't show anything since the data is not properly entered, but this is just to prove that its only the 1st script issue

**Comment by royspace** [comment]
You likely need to upgrade your gallery-dl to the latest version, and it should work. It’s working fine for me with both gallery-dl versions 1.27.1 and 1.28.2 @iWajdi

**Comment by iWajdi** [comment]
> You likely need to upgrade your gallery-dl to the latest version, and it should work. It’s working fine for me with both gallery-dl versions 1.27.1 and 1.28.2 @iWajdi

I made sure its 1.28.2 version and still the same. 
This is the most error I get all the time 
Processing URLs:   0% 0/716 [00:00<?, ?URL/s]
Traceback (most recent call last):
  File "/content/twitter-following-list-exporter/twitter-following-list-exporter.py", line 84, in <module>
    author_info = extract_author_info(json_data)
  File "/content/twitter-following-list-exporter/twitter-following-list-exporter.py", line 29, in extract_author_info
    author_info = data[0][1]['author']
TypeError: string indices must be integers

**Comment by royspace** [comment]
> > You likely need to upgrade your gallery-dl to the latest version, and it should work. It’s working fine for me with both gallery-dl versions 1.27.1 and 1.28.2 @iWajdi
> 
> I made sure its 1.28.2 version and still the same. This is the most error I get all the time Processing URLs: 0% 0/716 [00:00<?, ?URL/s] Traceback (most recent call last): File "/content/twitter-following-list-exporter/twitter-following-list-exporter.py", line 84, in author_info = extract_author_info(json_data) File "/content/twitter-following-list-exporter/twitter-following-list-exporter.py", line 29, in extract_author_info author_info = data[0][1]['author'] TypeError: string indices must be integers

Could you pull the latest code I just updated and try again? Also, make sure you successfully log in to Twitter with the config file by running this to check if it retrieves the list correctly.
```
gallery-dl -g https://x.com/YourUsername/following
```

**Comment by iWajdi** [comment]
I am using cookies.txt file instead to login, and I get a full list of followers and then I get another one converted.

**Comment by royspace** [comment]
Late reply, but this issue still seems to be caused by not logging into X correctly. To fix it, you can use a Chrome extension like [this one](https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc) and configure it in the config file:

```"cookies": "/Users/user/www.x.com_cookies.txt"```
